### ISSUE TITLE
Unablet to get started

### ISSUE THREAD

**Issue by HulluHevonen** [BitMEX/sample-market-maker#107]
I did all the steps from getting started, but when i try to run the market maker i get a list of errors
Importing symbol settings for XBTUSD...
Unable to find settings-XBTUSD.py.
2018-05-07 01:28:55,377 - INFO - market_maker - BitMEX Market Maker Version: v1.1

2018-05-07 01:28:55,377 - INFO - ws_thread - Connecting to wss://testnet.bitmex.com/realtime?subscribe=quote:XBTUSD,trade:XBTUSD,instrument,order:XBTUSD,execution:XBTUSD,margin,position
2018-05-07 01:28:55,377 - INFO - ws_thread - Authenticating with API Key.
2018-05-07 01:28:55,377 - INFO - ws_thread - Started thread
2018-05-07 01:28:55,830 - ERROR - ws_thread - API Key incorrect, please check and restart.
2018-05-07 01:28:55,830 - ERROR - _logging - close status: 31522
2018-05-07 01:28:55,830 - INFO - ws_thread - Websocket Closed
2018-05-07 01:28:56,377 - ERROR - ws_thread - Couldn't connect to WS! Exiting.

I double checked the API keys, they were correct, i tried making new API keys to no help.
What should i do?

**Comment by rohitgehe05** [comment]
try checking your api key permission, make sure it has the order permission set to true

**Comment by HulluHevonen** [comment]
It has both, order and read rights.

**Comment by rohitgehe05** [comment]
Try creating new keys and copy them again, faced this yesterday and this
method solved it.

Warm Regards,

Rohit Gehe
rohitgehe05@gmail.com
+91 7829 880 555

On 07-May-2018 at 7:17 PM, HulluHevonen <notifications@github.com> wrote:


It has both, order and read rights.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/BitMEX/sample-market-maker/issues/107#issuecomment-387070031>,
or mute the thread

**Comment by HulluHevonen** [comment]
Tried it. Didn't help.

**Comment by rohitgehe05** [comment]
Are you trying with the BitMEX API (Actual) or Testnet keys? Your `BASE_URL` seems to be pointing to the Testnet URL.

**Comment by HulluHevonen** [comment]
Testnet. I wanted to try it out so i figured testnet would be the place to do so.

**Comment by HulluHevonen** [comment]
It actually started to run on the third try. Thank you all for the support!

**Comment by speedsunxxp** [comment]
how did you fix this pls tell.

**Comment by Rik0lliskarkuri** [comment]
I changed nothing, i honestly have no clue how it eventually started, or what was the actual issue.

Sorry for the late answer and not really being of much help.

**Comment by HimanUK** [comment]
I understand I am super late to provide a fix for this. However, I wish to answer because I wasn't able to find a quick fix to this. When you install market_maker, you end up getting a marketmaker folder as well as a settings.py file OUTSIDE the folder. Adding the keys to this settings.py fixes the issue.

Hope this comes to help someone in the future.
