### ISSUE TITLE
Bitmex create order reminds the previous leverage ...

### ISSUE THREAD

**Issue by p0nt** [BitMEX/sample-market-maker#143]
So I have something weird over here, in the documentation of Bitmex they state that every order/position initiated will defaultly receive the cross leverage.

https://www.bitmex.com/app/isolatedMargin

"Note that, by default all positions are initially set to “Cross Margin”."

But for some reason If I have ever made a trade with leverage for example 5, it does not matter if this have been initiated with the api or the webinterface, the next order I initiate will automatically create a position with leverage 5.

This results in the following issue:

- If I would create the position with more value that I actually have it would still go through since the leverage is 5x by default, if I would like to switch back to a lower leverage (which I actually wanted from the start) it will show insufficient funds because I dont have enough BTC to put it on 1x....

I understand why it is not possible to add leverage into an order, but this seems to be a big bug here ....

**Comment by p0nt** [comment]
I can see that it is possible to change the leverage beforehand, therefore closed

**Comment by enriquepiatti** [comment]
The problem is that then we need *always* 2 requests before opening a new order/position
Normally you always want to set the leverage on a new order, but that is not possible with /order API, so we need to call first /position/leverage and then /order, I think will be much better to include leverage inside /order call !
